project:
  type: website

website:
  title: "rep3R"
  navbar:
    left:
      - href: index.qmd
        text: home
      - href: 2026/index.qmd
        text: current edition
      - text: past editions
        menu:
          - href: 2025/index.qmd
            text: "2025"

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



